const companyData = [
  {
    id: 1,
    name: "ADDQ",
    ITHSMatchar: false,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "ronn.elfors@addq.se",
    kontaktWebbsida: "",
    hemsida: "www.addq.se",
    utbildningar: ["WU", "ITP", ".NET", "JAVA", "FEU", "JSU", "APP"],
    beskrivning:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse, repudiandae.",
    ort: "Stockholm",
    synlig: true,
    timestamp: 3,
  },
  {
    id: 2,
    name: "Apendo",
    ITHSMatchar: false,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "",
    kontaktWebbsida: "http://apendo.se/internship/",
    hemsida: "http://apendo.se",
    utbildningar: [".NET", "JAVA", "JSU"],
    beskrivning:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo totam porro asperiores distinctio possimus? Dolorem.",
    ort: "Stockholm",
    synlig: true,
    timestamp: 10,
  },
  {
    id: 3,
    name: "Carismar",
    ITHSMatchar: false,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "work@carismar.com",
    kontaktWebbsida: "",
    hemsida: "www.carismar.com",
    utbildningar: ["JAVA"],
    beskrivning: "",
    ort: "Stockholm",
    synlig: true,
    timestamp: 1,
  },
  {
    id: 4,
    name: "Edaider",
    ITHSMatchar: true,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "",
    kontaktWebbsida: "",
    hemsida: "www.edaider.com",
    utbildningar: ["FEU"],
    beskrivning: "",
    ort: "Stockholm",
    synlig: true,
    timestamp: 6,
  },
  {
    id: 5,
    name: "EmbeddedArt AB",
    ITHSMatchar: false,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "rickard.randa-hedvall@embeddedart.se",
    kontaktWebbsida: "",
    hemsida: "www.embeddedart.se",
    utbildningar: [".NET"],
    beskrivning: "",
    ort: "Stockholm",
    synlig: true,
    timestamp: 19,
  },
  {
    id: 6,
    name: "HM",
    ITHSMatchar: true,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "",
    kontaktWebbsida: "",
    hemsida: "www.hm.se",
    utbildningar: [".NET", "FEU", "JSU"],
    beskrivning: "",
    ort: "Stockholm",
    synlig: true,
    timestamp: 14,
  },
  {
    id: 7,
    name: "Goodminton",
    ITHSMatchar: false,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "info@goodminton.se",
    kontaktWebbsida: "",
    hemsida: "www.goodminton.se",
    utbildningar: [],
    beskrivning: "",
    ort: "Stockholm",
    synlig: true,
    timestamp: 4,
  },
  {
    id: 8,
    name: "iGoMoon",
    ITHSMatchar: false,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "goran.berggren@igomoon.com",
    kontaktWebbsida: "",
    hemsida: "www.igomoon.com",
    utbildningar: ["WU"],
    beskrivning: "",
    ort: "Stockholm",
    synlig: true,
    timestamp: 11,
  },
  {
    id: 9,
    name: "Nibye",
    ITHSMatchar: false,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "alexandra@nibye.com",
    kontaktWebbsida: "",
    hemsida: "www.nibye.com",
    utbildningar: ["WU", "ITP", ".NET", "JAVA", "FEU", "JSU", "APP"],
    beskrivning: "",
    ort: "Stockholm",
    synlig: true,
    timestamp: 21,
  },
  {
    id: 10,
    name: "NS Ventures ",
    ITHSMatchar: false,
    ITHSMatcharBeskrivning: "",
    kontaktEpost: "patrik.lindkvist@nsventures.se ",
    kontaktWebbsida: "",
    hemsida: "https://www.nsventures.co/",
    utbildningar: ["FEU", "APP"],
    beskrivning:
      "Skicka CV och kort personligt brev. + skicka med exempel på kod som du tycker är ballt. Viktigt med rätt mindset. Företaget jobbar enbart med Flutter, och detta får du upplärning inom om du inte kan.",
    ort: "Stockholm",
    synlig: true,
    timestamp: 12,
  },
];

export default companyData;
